language: scala

scala:
  - 2.13.0

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update scalafmtCheckAll scalafmtSbtCheck compile test:compile coverage test:test coverageReport
  - find $HOME/.sbt -name "*.lock" | xargs rm

